use std::io::Read;

use bytemuck::checked::from_bytes;
use zendian::le::u16le;

use crate::cpu::{
    instructions::{
        arithmetic::{
            ADCInstruction, ADDInstruction, DAAInstruction, DECInstruction, INCInstruction,
            SBCInstruction, SUBInstruction,
        },
        bitwise::{
            CPLInstruction, RLAInstruction, RLCAInstruction, RRAInstruction, RRCAInstruction,
        },
        control::{
            CALLInstruction, HALTInstruction, JPInstruction, JRInstruction, NOPInstruction,
            RETIInstruction, RETInstruction, RSTInstruction, STOPInstruction,
        },
        flags::{CCFInstruction, DIInstruction, EIInstruction, SCFInstruction},
        load::{LDHInstruction, LDInstruction},
        logic::{ANDInstruction, ORInstruction, XORInstruction},
        stack::{POPInstruction, PUSHInstruction},
        test::CPInstruction,
        *,
    },
    operand::ConditionCode,
    registers::{Register8, Register16},
};

fn read_u8(src: &mut impl Read) -> Result<u8, std::io::Error> {
    let mut buf = [0u8];
    src.read_exact(&mut buf)?;
    Ok(buf[0])
}

fn read_i8(src: &mut impl Read) -> Result<i8, std::io::Error> {
    let byte = read_u8(src)?;
    Ok(byte as i8)
}

fn read_u16le(src: &mut impl Read) -> Result<u16, std::io::Error> {
    let mut buf = [0u8; 2];
    src.read_exact(&mut buf)?;
    Ok(u16le::from_bits(*from_bytes(&buf)).bits())
}

pub fn read_instruction(src: &mut impl Read) -> Result<Instruction, std::io::Error> {
    let opcode = read_u8(src)?;

    Ok(match opcode {
        0x00 => NOPInstruction::Empty.into(),
        0x01 => LDInstruction::R16N16(Register16::BC, read_u16le(src)?).into(),
        0x02 => LDInstruction::R16A(Register16::BC).into(),
        0x03 => INCInstruction::R16(Register16::BC).into(),
        0x04 => INCInstruction::R8(Register8::B).into(),
        0x05 => DECInstruction::R8(Register8::B).into(),
        0x06 => LDInstruction::R8N8(Register8::B, read_u8(src)?).into(),
        0x07 => RLCAInstruction::Empty.into(),
        0x08 => LDInstruction::N16SP(read_u16le(src)?).into(),
        0x09 => ADDInstruction::HLR16(Register16::BC).into(),
        0x0A => LDInstruction::AR16(Register16::BC).into(),
        0x0B => DECInstruction::R16(Register16::BC).into(),
        0x0C => INCInstruction::R8(Register8::C).into(),
        0x0D => DECInstruction::R8(Register8::C).into(),
        0x0E => LDInstruction::R8N8(Register8::C, read_u8(src)?).into(),
        0x0F => RRCAInstruction::Empty.into(),

        0x10 => {
            let _ = read_u8(src)?;
            STOPInstruction::Empty.into()
        }
        0x11 => LDInstruction::R16N16(Register16::DE, read_u16le(src)?).into(),
        0x12 => LDInstruction::R16A(Register16::DE).into(),
        0x13 => INCInstruction::R16(Register16::DE).into(),
        0x14 => INCInstruction::R8(Register8::D).into(),
        0x15 => DECInstruction::R8(Register8::D).into(),
        0x16 => LDInstruction::R8N8(Register8::D, read_u8(src)?).into(),
        0x17 => RLAInstruction::Empty.into(),
        0x18 => JRInstruction::E8(read_i8(src)?).into(),
        0x19 => ADDInstruction::HLR16(Register16::DE).into(),
        0x1A => LDInstruction::AR16(Register16::DE).into(),
        0x1B => DECInstruction::R16(Register16::DE).into(),
        0x1C => INCInstruction::R8(Register8::E).into(),
        0x1D => DECInstruction::R8(Register8::E).into(),
        0x1E => LDInstruction::R8N8(Register8::E, read_u8(src)?).into(),
        0x1F => RRAInstruction::Empty.into(),

        0x20 => JRInstruction::CCE8(ConditionCode::NZ, read_i8(src)?).into(),
        0x21 => LDInstruction::R16N16(Register16::HL, read_u16le(src)?).into(),
        0x22 => LDInstruction::HLIA.into(),
        0x23 => INCInstruction::R16(Register16::HL).into(),
        0x24 => INCInstruction::R8(Register8::H).into(),
        0x25 => DECInstruction::R8(Register8::H).into(),
        0x26 => LDInstruction::R8N8(Register8::H, read_u8(src)?).into(),
        0x27 => DAAInstruction::Empty.into(),
        0x28 => JRInstruction::CCE8(ConditionCode::Z, read_i8(src)?).into(),
        0x29 => ADDInstruction::HLR16(Register16::HL).into(),
        0x2A => LDInstruction::AHLI.into(),
        0x2B => DECInstruction::HL.into(),
        0x2C => INCInstruction::R8(Register8::L).into(),
        0x2D => DECInstruction::R8(Register8::L).into(),
        0x2E => LDInstruction::R8N8(Register8::L, read_u8(src)?).into(),
        0x2F => CPLInstruction::Empty.into(),

        0x30 => JRInstruction::CCE8(ConditionCode::NC, read_i8(src)?).into(),
        0x31 => LDInstruction::SPN16(read_u16le(src)?).into(),
        0x32 => LDInstruction::HLDA.into(),
        0x33 => INCInstruction::SP.into(),
        0x34 => INCInstruction::HL.into(),
        0x35 => DECInstruction::HL.into(),
        0x36 => LDInstruction::HLN8(read_u8(src)?).into(),
        0x37 => SCFInstruction::Empty.into(),
        0x38 => JRInstruction::CCE8(ConditionCode::C, read_i8(src)?).into(),
        0x39 => ADDInstruction::HLSP.into(),
        0x3A => LDInstruction::AHLD.into(),
        0x3B => DECInstruction::SP.into(),
        0x3C => INCInstruction::R8(Register8::A).into(),
        0x3D => DECInstruction::R8(Register8::A).into(),
        0x3E => LDInstruction::R8N8(Register8::A, read_u8(src)?).into(),
        0x3F => CCFInstruction::Empty.into(),

        0x40 => LDInstruction::R8R8(Register8::B, Register8::B).into(),
        0x41 => LDInstruction::R8R8(Register8::B, Register8::C).into(),
        0x42 => LDInstruction::R8R8(Register8::B, Register8::D).into(),
        0x43 => LDInstruction::R8R8(Register8::B, Register8::E).into(),
        0x44 => LDInstruction::R8R8(Register8::B, Register8::H).into(),
        0x45 => LDInstruction::R8R8(Register8::B, Register8::L).into(),
        0x46 => LDInstruction::R8HL(Register8::B).into(),
        0x47 => LDInstruction::R8R8(Register8::B, Register8::A).into(),
        0x48 => LDInstruction::R8R8(Register8::C, Register8::B).into(),
        0x49 => LDInstruction::R8R8(Register8::C, Register8::C).into(),
        0x4A => LDInstruction::R8R8(Register8::C, Register8::D).into(),
        0x4B => LDInstruction::R8R8(Register8::C, Register8::E).into(),
        0x4C => LDInstruction::R8R8(Register8::C, Register8::H).into(),
        0x4D => LDInstruction::R8R8(Register8::C, Register8::L).into(),
        0x4E => LDInstruction::R8HL(Register8::C).into(),
        0x4F => LDInstruction::R8R8(Register8::C, Register8::A).into(),

        0x50 => LDInstruction::R8R8(Register8::D, Register8::B).into(),
        0x51 => LDInstruction::R8R8(Register8::D, Register8::C).into(),
        0x52 => LDInstruction::R8R8(Register8::D, Register8::D).into(),
        0x53 => LDInstruction::R8R8(Register8::D, Register8::E).into(),
        0x54 => LDInstruction::R8R8(Register8::D, Register8::H).into(),
        0x55 => LDInstruction::R8R8(Register8::D, Register8::L).into(),
        0x56 => LDInstruction::R8HL(Register8::D).into(),
        0x57 => LDInstruction::R8R8(Register8::D, Register8::A).into(),
        0x58 => LDInstruction::R8R8(Register8::E, Register8::B).into(),
        0x59 => LDInstruction::R8R8(Register8::E, Register8::C).into(),
        0x5A => LDInstruction::R8R8(Register8::E, Register8::D).into(),
        0x5B => LDInstruction::R8R8(Register8::E, Register8::E).into(),
        0x5C => LDInstruction::R8R8(Register8::E, Register8::H).into(),
        0x5D => LDInstruction::R8R8(Register8::E, Register8::L).into(),
        0x5E => LDInstruction::R8HL(Register8::E).into(),
        0x5F => LDInstruction::R8R8(Register8::E, Register8::A).into(),

        0x60 => LDInstruction::R8R8(Register8::H, Register8::B).into(),
        0x61 => LDInstruction::R8R8(Register8::H, Register8::C).into(),
        0x62 => LDInstruction::R8R8(Register8::H, Register8::D).into(),
        0x63 => LDInstruction::R8R8(Register8::H, Register8::E).into(),
        0x64 => LDInstruction::R8R8(Register8::H, Register8::H).into(),
        0x65 => LDInstruction::R8R8(Register8::H, Register8::L).into(),
        0x66 => LDInstruction::R8HL(Register8::H).into(),
        0x67 => LDInstruction::R8R8(Register8::H, Register8::A).into(),
        0x68 => LDInstruction::R8R8(Register8::L, Register8::B).into(),
        0x69 => LDInstruction::R8R8(Register8::L, Register8::C).into(),
        0x6A => LDInstruction::R8R8(Register8::L, Register8::D).into(),
        0x6B => LDInstruction::R8R8(Register8::L, Register8::E).into(),
        0x6C => LDInstruction::R8R8(Register8::L, Register8::H).into(),
        0x6D => LDInstruction::R8R8(Register8::L, Register8::L).into(),
        0x6E => LDInstruction::R8HL(Register8::L).into(),
        0x6F => LDInstruction::R8R8(Register8::L, Register8::A).into(),

        0x70 => LDInstruction::HLR8(Register8::B).into(),
        0x71 => LDInstruction::HLR8(Register8::C).into(),
        0x72 => LDInstruction::HLR8(Register8::D).into(),
        0x73 => LDInstruction::HLR8(Register8::E).into(),
        0x74 => LDInstruction::HLR8(Register8::H).into(),
        0x75 => LDInstruction::HLR8(Register8::L).into(),
        0x76 => HALTInstruction::Empty.into(),
        0x77 => LDInstruction::HLR8(Register8::A).into(),
        0x78 => LDInstruction::R8R8(Register8::A, Register8::B).into(),
        0x79 => LDInstruction::R8R8(Register8::A, Register8::C).into(),
        0x7A => LDInstruction::R8R8(Register8::A, Register8::D).into(),
        0x7B => LDInstruction::R8R8(Register8::A, Register8::E).into(),
        0x7C => LDInstruction::R8R8(Register8::A, Register8::H).into(),
        0x7D => LDInstruction::R8R8(Register8::A, Register8::L).into(),
        0x7E => LDInstruction::R8HL(Register8::A).into(),
        0x7F => LDInstruction::R8R8(Register8::A, Register8::A).into(),

        0x80 => ADDInstruction::AR8(Register8::B).into(),
        0x81 => ADDInstruction::AR8(Register8::C).into(),
        0x82 => ADDInstruction::AR8(Register8::D).into(),
        0x83 => ADDInstruction::AR8(Register8::E).into(),
        0x84 => ADDInstruction::AR8(Register8::H).into(),
        0x85 => ADDInstruction::AR8(Register8::L).into(),
        0x86 => ADDInstruction::AHL.into(),
        0x87 => ADDInstruction::AR8(Register8::A).into(),
        0x88 => ADCInstruction::AR8(Register8::B).into(),
        0x89 => ADCInstruction::AR8(Register8::C).into(),
        0x8A => ADCInstruction::AR8(Register8::D).into(),
        0x8B => ADCInstruction::AR8(Register8::E).into(),
        0x8C => ADCInstruction::AR8(Register8::H).into(),
        0x8D => ADCInstruction::AR8(Register8::L).into(),
        0x8E => ADCInstruction::AHL.into(),
        0x8F => ADCInstruction::AR8(Register8::A).into(),

        0x90 => SUBInstruction::AR8(Register8::B).into(),
        0x91 => SUBInstruction::AR8(Register8::C).into(),
        0x92 => SUBInstruction::AR8(Register8::D).into(),
        0x93 => SUBInstruction::AR8(Register8::E).into(),
        0x94 => SUBInstruction::AR8(Register8::H).into(),
        0x95 => SUBInstruction::AR8(Register8::L).into(),
        0x96 => SUBInstruction::AHL.into(),
        0x97 => SUBInstruction::AR8(Register8::A).into(),
        0x98 => SBCInstruction::AR8(Register8::B).into(),
        0x99 => SBCInstruction::AR8(Register8::C).into(),
        0x9A => SBCInstruction::AR8(Register8::D).into(),
        0x9B => SBCInstruction::AR8(Register8::E).into(),
        0x9C => SBCInstruction::AR8(Register8::H).into(),
        0x9D => SBCInstruction::AR8(Register8::L).into(),
        0x9E => SBCInstruction::AHL.into(),
        0x9F => SBCInstruction::AR8(Register8::A).into(),

        0xA0 => ANDInstruction::AR8(Register8::B).into(),
        0xA1 => ANDInstruction::AR8(Register8::C).into(),
        0xA2 => ANDInstruction::AR8(Register8::D).into(),
        0xA3 => ANDInstruction::AR8(Register8::E).into(),
        0xA4 => ANDInstruction::AR8(Register8::H).into(),
        0xA5 => ANDInstruction::AR8(Register8::L).into(),
        0xA6 => ANDInstruction::AHL.into(),
        0xA7 => ANDInstruction::AR8(Register8::A).into(),
        0xA8 => XORInstruction::AR8(Register8::B).into(),
        0xA9 => XORInstruction::AR8(Register8::C).into(),
        0xAA => XORInstruction::AR8(Register8::D).into(),
        0xAB => XORInstruction::AR8(Register8::E).into(),
        0xAC => XORInstruction::AR8(Register8::H).into(),
        0xAD => XORInstruction::AR8(Register8::L).into(),
        0xAE => XORInstruction::AHL.into(),
        0xAF => XORInstruction::AR8(Register8::A).into(),

        0xB0 => ORInstruction::AR8(Register8::B).into(),
        0xB1 => ORInstruction::AR8(Register8::C).into(),
        0xB2 => ORInstruction::AR8(Register8::D).into(),
        0xB3 => ORInstruction::AR8(Register8::E).into(),
        0xB4 => ORInstruction::AR8(Register8::H).into(),
        0xB5 => ORInstruction::AR8(Register8::L).into(),
        0xB6 => ORInstruction::AHL.into(),
        0xB7 => ORInstruction::AR8(Register8::A).into(),
        0xB8 => CPInstruction::AR8(Register8::B).into(),
        0xB9 => CPInstruction::AR8(Register8::C).into(),
        0xBA => CPInstruction::AR8(Register8::D).into(),
        0xBB => CPInstruction::AR8(Register8::E).into(),
        0xBC => CPInstruction::AR8(Register8::H).into(),
        0xBD => CPInstruction::AR8(Register8::L).into(),
        0xBE => CPInstruction::AHL.into(),
        0xBF => CPInstruction::AR8(Register8::A).into(),

        0xC0 => RETInstruction::Conditional(ConditionCode::NZ).into(),
        0xC1 => POPInstruction::R16(Register16::BC).into(),
        0xC2 => JPInstruction::CCN16(ConditionCode::NZ, read_u16le(src)?).into(),
        0xC3 => JPInstruction::N16(read_u16le(src)?).into(),
        0xC4 => CALLInstruction::CCN16(ConditionCode::NZ, read_u16le(src)?).into(),
        0xC5 => PUSHInstruction::R16(Register16::BC).into(),
        0xC6 => ADDInstruction::AN8(read_u8(src)?).into(),
        0xC7 => RSTInstruction::ResetVector(ResetVector::Addr00).into(),
        0xC8 => RETInstruction::Conditional(ConditionCode::Z).into(),
        0xC9 => RETInstruction::Unconditional.into(),
        0xCA => JPInstruction::CCN16(ConditionCode::Z, read_u16le(src)?).into(),
        0xCB => todo!("Prefixed instructions"),
        0xCC => CALLInstruction::CCN16(ConditionCode::Z, read_u16le(src)?).into(),
        0xCD => CALLInstruction::N16(read_u16le(src)?).into(),
        0xCE => ADCInstruction::AN8(read_u8(src)?).into(),
        0xCF => RSTInstruction::ResetVector(ResetVector::Addr08).into(),

        0xD0 => RETInstruction::Conditional(ConditionCode::NC).into(),
        0xD1 => POPInstruction::R16(Register16::DE).into(),
        0xD2 => JPInstruction::CCN16(ConditionCode::NC, read_u16le(src)?).into(),
        0xD3 => todo!("Illegal instruction D3"),
        0xD4 => CALLInstruction::CCN16(ConditionCode::NC, read_u16le(src)?).into(),
        0xD5 => PUSHInstruction::R16(Register16::DE).into(),
        0xD6 => SUBInstruction::AN8(read_u8(src)?).into(),
        0xD7 => RSTInstruction::ResetVector(ResetVector::Addr10).into(),
        0xD8 => RETInstruction::Conditional(ConditionCode::C).into(),
        0xD9 => RETIInstruction::Empty.into(),
        0xDA => JPInstruction::CCN16(ConditionCode::C, read_u16le(src)?).into(),
        0xDB => todo!("Illegal instruction DB"),
        0xDC => CALLInstruction::CCN16(ConditionCode::C, read_u16le(src)?).into(),
        0xDD => todo!("Illegal instruction DD"),
        0xDE => SBCInstruction::AN8(read_u8(src)?).into(),
        0xDF => RSTInstruction::ResetVector(ResetVector::Addr18).into(),

        0xE0 => LDHInstruction::N8A(read_u8(src)?).into(),
        0xE1 => POPInstruction::R16(Register16::HL).into(),
        0xE2 => LDHInstruction::CA.into(),
        0xE3 => todo!("Illegal instruction E3"),
        0xE4 => todo!("Illegal instruction E4"),
        0xE5 => PUSHInstruction::R16(Register16::HL).into(),
        0xE6 => ANDInstruction::AN8(read_u8(src)?).into(),
        0xE7 => RSTInstruction::ResetVector(ResetVector::Addr20).into(),
        0xE8 => ADDInstruction::SPE8(read_i8(src)?).into(),
        0xE9 => JPInstruction::HL.into(),
        0xEA => LDInstruction::N16A(read_u16le(src)?).into(),
        0xEB => todo!("Illegal instruction EB"),
        0xEC => todo!("Illegal instruction EC"),
        0xED => todo!("Illegal instruction ED"),
        0xEE => XORInstruction::AN8(read_u8(src)?).into(),
        0xEF => RSTInstruction::ResetVector(ResetVector::Addr28).into(),

        0xF0 => LDHInstruction::AN8(read_u8(src)?).into(),
        0xF1 => POPInstruction::AF.into(),
        0xF2 => LDHInstruction::AC.into(),
        0xF3 => DIInstruction::Empty.into(),
        0xF4 => todo!("Illegal instruction F4"),
        0xF5 => PUSHInstruction::AF.into(),
        0xF6 => ORInstruction::AN8(read_u8(src)?).into(),
        0xF7 => RSTInstruction::ResetVector(ResetVector::Addr30).into(),
        0xF8 => LDInstruction::HLSPE8(read_i8(src)?).into(),
        0xF9 => LDInstruction::SPHL.into(),
        0xFA => LDInstruction::AN16(read_u16le(src)?).into(),
        0xFB => EIInstruction::Empty.into(),
        0xFC => todo!("Illegal instruction FC"),
        0xFD => todo!("Illegal instruction FD"),
        0xFE => CPInstruction::AN8(read_u8(src)?).into(),
        0xFF => RSTInstruction::ResetVector(ResetVector::Addr38).into(),
    })
}
